# Generated by Django 4.1.13 on 2024-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_profile_githubusername_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dipxdfu0l/image/upload/v1709322839/default_avatar_otcxu1.jpg', max_length=255),
        ),
    ]
